// lib/firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
          'This app only supports Web and Android platforms.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macOS - '
          'This app only supports Web and Android platforms.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'This app only supports Web and Android platforms.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'This app only supports Web and Android platforms.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwaPqmEV0UPdPPMV351GXPycDvjgoF5UE',
    appId: '1:858998050859:web:18f337fe2c7e6ef8071a6e',
    messagingSenderId: '858998050859',
    projectId: 'sparewoapp',
    authDomain: 'sparewoapp.firebaseapp.com',
    storageBucket: 'sparewoapp.firebasestorage.app',
    measurementId: 'G-HSRDQ4R89M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwaPqmEV0UPdPPMV351GXPycDvjgoF5UE',
    appId: '1:858998050859:android:bc7c8857ea7699eb071a6e',
    messagingSenderId: '858998050859',
    projectId: 'sparewoapp',
    storageBucket: 'sparewoapp.firebasestorage.app',
  );
}
